package com.dashdocapi.interfaces.enums;

public enum ServiceType {
    SPEECH_THERAPY, OCCUPATIONAL_THERAPY, PHYSICAL_THERAPY, COUNSELING, PSYCHOLOGICAL, HEARING_SERIVCE, VISION_THERAPY, ASSISTIVE_TECHNOLOGY, SETTS;
}
