package com.dashdocnow.interfaces.enums;

public enum DocumentType {
  THERAPY_ARTICULATION,
    THERAPY_VOICE,
    THERAPY_FEEDING_SWALLOWING,
    THERAPY_EXPRESSIVE_LANGUAGE,
    THERAPY_RECEPTIVE_LANGUAGE,
    THERAPY_SOCIAL_LANGUAGE,
    THERAPY_SPEECH_LANGUAGE,
    THERAPY_FLUENCY,
    THERAPY_CONSENT_FORMS,
    THERAPY_NOTES,
    ASSESSMENT_ARTICULATION,
    ASSESSMENT_VOICE,
    ASSESSMENT_FEEDING_SWALLOWING,
    ASSESSMENT_EXPRESSIVE_LANGUAGE,
    ASSESSMENT_RECEPTIVE_LANGUAGE,
    ASSESSMENT_SOCIAL_LANGUAGE,
    ASSESSMENT_SPEECH_LANGUAGE,
    ASSESSMENT_FLUENCY,
    ASSESSMENT_CONSENT_FORMS,
    ASSESSMENT_GENERAL,
    SCREENERS,
  ONBOARDING_FORMS
}
