name: Client unit-tests

env:
  NODE_VERSION: '18'

on:
  push:
    branches: [ "develop", "release/**", "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  run-client-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashdoc-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm install
          npm run build
          npm run test
