name: Dev Deployment

on:
  push:
    branches: [ "test-eb" ]

env:
  DOTNET_VERSION: '8.x'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Dashdoc.API

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: |
        dotnet publish -c Release --output "${{ github.workspace }}/${{github.run_id}}"
        cd ${{github.run_id}}
        zip -r ../${{github.run_id}}.zip .
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.3
      with: 
        name: deploy-files
        path: ${{github.run_id}}.zip
  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4.1.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.ELASTIC_BEANSTALK_NAME }}
        environment_name: ${{ secrets.ELASTIC_BEANSTALK_ENV_NAME }}
        version_label: ${{github.SHA}}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: ${{github.run_id}}.zip