name: Develop Deployment

on:
  push:
    branches: [ "test" ]

env:
  NODE_VERSION: '18'
  DOTNET_VERSION: '8.x'
  PROJECT_LOCATION: Dashdoc.API/Dashdoc.API.Server.csproj
  ELASTIC_BEANSTALK_NAME: dotnet-linux
  ELASTIC_BEANSTALK_ENV_NAME: Dotnet-linux-env

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: $DOTNET_VERSION
    - name: Restore dependencies
      run: dotnet restore $PROJECT_LOCATION
    - name: Build
      run: dotnet build --no-restore $PROJECT_LOCATION
    - name: Pack
      run: |
        dotnet publish $PROJECT_LOCATION -c Release --output "${{ github.workspace }}/${{github.run_id}}"
        cd ${{github.run_id}}
        zip -r ../${{github.run_id}}.zip .
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.3
      with: 
        name: deploy-files
        path: ${{github.run_id}}.zip
  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4.1.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}