name: API unit-tests

env:
  JDK_VERSION: '17'

on:
  push:
    branches: [ "develop", "release/**", "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bookitapi

    name: Build and Test (Develop)
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ env.JDK_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: 'temurin'
        cache: maven
    - name: Run unit tests
      run: mvn -B test
      env: 
          PROFILE: test
          DATASOURCE: ${{ secrets.DATASOURCE }}
          DATASOURCE_DRIVER: ${{secrets.DATASOURCE_DRIVER}}
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          COGNITO_JWK_URI: ${{ secrets.COGNITO_JWK_URI }}
          NOTIFICATIONS_NUMBER: ${{ secrets.NOTIFICATIONS_NUMBER }}
          NOTIFICATIONS_EMAIL: ${{ secrets.NOTIFICATIONS_EMAIL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: bookitapi